# 2017 May 25
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
language: node_js
node_js:
  - "7"
cache:
  directories:
    - $HOME/.npm  # npm's cache
    - $HOME/.yarn-cache  # yarn's cache
install:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-upgrade-npm.bash)"
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-deploy.bash)"
notifications:
  slack:
    secure: nAAs02f2LHKm9/sLJBCYz9mVmH9WbGx0jFPpOX4maObPE6SlzLN6ucXyRuPzlNlDlvc5YY+19xdsPWrZ4tubPkBWdlUpxQxQYF4kCmkqY/M4Csa9+ThcjT7A/qb0oVmevFbRgJpjTEhQBWoRMfs0jzlotmwWx8QunDYOY3C89F4=
  email:
    recipients:
      secure: Mh0vdmlNlBqFC5vCGAbt3q+TNAuIOD6yAMa0NbnwasSDtFZte11NkGZyGUAYvZorVwpugzym79niSHkniY5r5VmvrJWVefRTzctvJde1ha7+uCguozVVG0qGC6lk7S/3tqRvc5FVYFs2mQysD0XXySpO1WQuBlV5xt3v3t88fBQ=
