sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/7af8b26/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/7af8b26/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/7af8b26/scripts/deploy-now.bash)"
notifications:
  email:
    recipients:
      secure: NG/r3roaEZwVg7UAtGgdfL6EpZWKVk9xQhB+Bc4iTat59ojWCEkyxHrJLzY4Wl7xrms15bC8tzuTmUyOx14EbFNO0bI9mh2PNOFqEM+2VhY5jLXgE2K7Jh4EJGINABWB8v8nqnVpg2TKsRY5FeQsdm2nc5tbMnuSMAbJ1PyslsA=
