# August 25, 2015
# https://docpad.org/docs/deploy

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - 4
cache:
  directories:
    - node_modules

# Prepare and run our tests
script: "npm test"

# Custom Notifications
# travis encrypt --org "$TRAVIS_NOTIFICATION_EMAIL" --add notifications.email.recipients
# travis encrypt --org "$SLACK_SUBDOMAIN:$SLACK_TRAVIS_TOKEN#updates" --add notifications.slack
notifications:
  email:
    recipients:
      secure: Sb7rPIkJX+yoTiijDXBu63uXX/y+wFDv39V1KfWwcPVIlEnIfDgEqlhhl0LW5BFrdVOwJhj+UR0cF0qIR5CWZYLy8kKgJcRIvPpTVDXiz1Yl4YJ22wnbQgmvJOOaFRHsAa8wLBs3fzppsaIxhXa6RPRUeqOOxIhs0Sfne50uChs=
  slack:
    secure: JM/9Tk+5MX4IE8Wk7MzoYkZrbKkg/BOLGvq0xZ18ODuKUBds/laYO/2r/eZb9ffszKddn24eBeGFQj2qVSSK7QmTBUh+RQnqt3Dyj2iW4Xb/Ba33wetXwxlKiwWANrdVIg+A9ewmERWjRte2u1HQUi1HQJoE0EOxgx46Mhe/p1I=

# Deployment
after_success: >
  if ([ ! -z "$DEPLOY_TOKEN" ] &&
      [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] &&
      [ -z "$TRAVIS_TAG" ] &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    echo "Deploying";
    git config --global user.email "$DEPLOY_EMAIL";
    git config --global user.name "$DEPLOY_NAME";
    git remote rm origin;
    git remote add origin "https://$DEPLOY_USER:$DEPLOY_TOKEN@github.com/$TRAVIS_REPO_SLUG.git";
    npm run-script deploy;
    echo "Deployed";
  else
    echo "Skipped deploy"
  fi

# Custom Configuration
env:
  global:
    # deployment environment variables
    # travis encrypt "DEPLOY_USER=$GITHUB_USERNAME" --add env.global
    # travis encrypt "DEPLOY_TOKEN=$GITHUB_TRAVIS_TOKEN" --add env.global
    - DEPLOY_BRANCH='master'  # this is the branch name that you want tested and deployed, set correctly
    - DEPLOY_NAME='Travis CI Deployer'  # this is the name that is used for the deployment commit, set to whatever
    - DEPLOY_EMAIL='deployer@travis-ci.org'  # this is the email that is used for the deployment commit, set to whatever
    - secure: UtujwEOckPjTaBX2PcZztFQv5thnCheG4DubLypWpArr9ldMAkaGoBP1d9B3Te+hB1WjUy3AFh3A731e5is+KzRXJlFRhP/nacXW8MLTIQkUoKgDFyjLaq8R/t3KefArXqMQ3S27KXem8cSbw74hauKLkYb5hld6dWydOY5lfB8=
    - secure: EP2W35Sro9fvtwrBb91ATu8PvZ7orn2e1/iKj9SkHM+/nxzVty0DrXuH2CREG72NulVDH7EoXsk32nUFzZEu5m12UNEbBjr++GLm+NGv7Of+2GdzRJWkk33j/0+Oa9auocFZZGG7olWjEupdLnlnir2Oecgy/p6OZR1lWZc7bEA=
    # application environment variables
    # travis encrypt "BEVRY_GITHUB_CLIENT_ID=$BEVRY_GITHUB_CLIENT_ID" --add env.global
    # travis encrypt "BEVRY_GITHUB_CLIENT_SECRET=$BEVRY_GITHUB_CLIENT_SECRET" --add env.global
    # travis encrypt "BEVRY_STRIPE_PUBLIC_KEY=$BEVRY_STRIPE_PUBLIC_KEY" --add env.global
    # travis encrypt "BEVRY_STRIPE_SECRET_KEY=$BEVRY_STRIPE_SECRET_KEY" --add env.global
    - secure: VaWxs+0jAzVy1wNsa/5ugGBWVtLjB9QU5IPD8Y1RXlVbKhDxR56YTXFH8s22d3IW1dmnAqSgCixcToXCeA0UO/HNXD3aG7d4muvU+1lS3CDB5nUUeIQoy/gU94YL+RY2JBZzgN/XG9dEWUB1NvmYVVEzpu+Ofq84AsrgfSYlDrk=
    - secure: Bw7QEa088jRGrRmct9zCwv6ZDwdCva5gwS4YmdFqwjKm3Aeug/gZN+0bUEXiESiq8S0Irvwb0K8PkJajqV4JKtCZ9Xk/DXhQmJ2k75ChY07eeTgACTUTlpMKHJ61aw7MFJofQ03Og49QcG72ETlFuvTFogbZVqP0sOd5lCCTF+8=
    - secure: H3EVzfBRt0Lo9q9v1aahDFNT9Uz12tKbPQnRjiEGH+Ir9woeg9Kj/kFrgJWXADIhgyRNzOkpeuaa3j5d57l26LZzaJBZwKyL4ZbiR/WkwXOWQoDoSC3dE6zveCqJkLz/Ec9HbW6v8+2oLgP6CJ3B8HO2gBUWcnhYF4lUop9Vclw=
    - secure: hpwiMDE5m+KLu9nZ5dsKlLoYqMNc/m1ZxHkIIgf805IhN9gKv0U+LRM+lSeQk10Gq2nZ8J/N3vorxuZR81izn3aKNfF+PbymsvJY2tF83GE19f0rJii/alQmvBP404uYFtDyNmtoM1frg6qYe5a0OvpZaOqBB7k1+M3Tw9C/zZ8=
